<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>FRM SLIM</title>


        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>



        <div class="container">

           <center> <h1>List employees</h1></center>


            <form class="form-inline" action="" method="GET">
                <div class="form-group">
                    <label for="exampleInputEmail2">Search email: </label>
                    <input type="text" class="form-control" name="email" placeholder="email">
                </div>
                <button type="submit" class="btn btn-danger">Buscar</button>
            </form>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>NAME</th>
                        <th>EMAIL</th>
                        <th>POSITION</th>
                        <th>SALARY</th>
                        <th>OPTION</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($employees as $employee) : ?>
                        <tr>
                            <td><?= $employee['name'] ?></td>
                            <td><?= $employee['email'] ?></td>
                            <td><?= $employee['position'] ?></td>
                            <td><?= $employee['salary'] ?></td>
                            <td>
                                <button class="btn btn-danger" data-toggle="modal" data-target="#modal<?= $employee['id'] ?>">Ver más</button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div><!-- /.container -->

        <?php foreach ($employees as $employee) : ?>
        <div class="modal fade" id="modal<?= $employee['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Información completa</h4>
                    </div>
                    <div class="modal-body">
                        <strong><p>Datos del empleado seleccionado:</p></strong>
                        <table class="table table-striped">
                        <tr>
                            <td>Nombre:</td>
                            <td><?= $employee['name'] ?></td>
                        </tr>
                        <tr>
                            <td>E-mail:</td>
                            <td><?= $employee['email'] ?></td>
                        </tr>
                        <tr>
                            <td>Teléfono:</td>
                            <td> <?= $employee['phone'] ?></td>
                        </tr>
                        <tr>
                            <td>Dirección:</td>
                            <td><?= $employee['address'] ?></td>
                        </tr>
                        <tr>
                            <td>Cargo:</td>
                            <td> <?= $employee['position'] ?></td>
                        </tr>
                        <tr>
                            <td>Skills:</td>
                            <td>
                                <?php foreach ($employee['skills'] as $skill): ?>
                                        <?= $skill['skill'] ?> -
                                    <?php endforeach; ?>
                            </td>
                        </tr>
                        </table>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Aceptar</button>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach; ?>


        <!-- Latest compiled and minified JavaScript -->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>
